name: Docker Operations via Makefile

on:
  push:
    branches:
      - main

jobs:
  docker-operations:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Run Makefile targets
      run: |
        make docker-buildx IMG=${{ secrets.DOCKER_USERNAME }}/route53pilot:latest

    - name: Logout from Docker
      if: always()
      run: docker logout
